### ISSUE TITLE
Support classpath: URLs in 'extractorsDir'

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-linkmove#5]
Currently `LinkMoveFactory.extractorsDir` is a String that is treated as a File path by LinkMove. However LM also support `ClasspathExtractorModelLoader`. So let's change 'extractorsDir' to a FolderResourceFactory, and analyze returned URL, configuring LM for either  "file:" or "classpath:" URLs (and throwing on URLs that are of any other kind).

**Comment by ebondareva** [comment]
The 'extracrorsDir' has been replaced with FolderResourceFactory but a new issue has arisen: extracotrs xml files aren't available inside the jar. Proposed solution is to extend API of LmRuntimeBuilder with extractorModelsRoot(URI) to take the right IExtractorModelLoader in relation to protocol 'classpath:' or 'file:' (LmRuntimeBuilder.bindModelLoader(...)).
